package ideas

var DEFAULT_CONCEPT_REPO = ConceptsRepository{
	ID:   "vczncfpjwr",
	dict: map[string]*Concept{},
}

func init() {
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_NOT_DETECTED)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_DETECTED)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_DATA_NOT_AVAILABLE)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_DATA_NEEDED)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_APPLICABLE_HERE)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_NOT_APPLICABLE_HERE)
	//----------
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_RBC_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_WBC_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_HEMOLOBIN_CONCENTRATION)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_MVC)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_MCH)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_MCHC)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_PLATELET_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_NEUTROPHIL_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_LYMPHOCYTE_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_MONOCYTE_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_EOSINOPHIL_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_BASOPHIL_COUNT)
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_RETICULOCYTE_COUNT)
	//------------
	// DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_CBC)
	// DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_PERIPHERAL_BLOOD_FILM_FINDINGS)
	//------------
	DEFAULT_CONCEPT_REPO.SetConcept(CONCEPT_WEATHER_IS_RAINING)
}
