package ideas

var DEFAULT_CONCEPT_REPO = ConceptsRepository{}

func init() {
	DEFAULT_CONCEPT_REPO[CONCEPT_NOT_DETECTED.ID] = &CONCEPT_NOT_DETECTED
	DEFAULT_CONCEPT_REPO[CONCEPT_DETECTED.ID] = &CONCEPT_DETECTED
	DEFAULT_CONCEPT_REPO[CONCEPT_DATA_NOT_AVAILABLE.ID] = &CONCEPT_DATA_NOT_AVAILABLE
	DEFAULT_CONCEPT_REPO[CONCEPT_DATA_NEEDED.ID] = &CONCEPT_DATA_NEEDED
	DEFAULT_CONCEPT_REPO[CONCEPT_APPLICABLE_HERE.ID] = &CONCEPT_APPLICABLE_HERE
	DEFAULT_CONCEPT_REPO[CONCEPT_NOT_APPLICABLE_HERE.ID] = &CONCEPT_NOT_APPLICABLE_HERE
	DEFAULT_CONCEPT_REPO[CONCEPT_RBC_COUNT.ID] = &CONCEPT_RBC_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_WBC_COUNT.ID] = &CONCEPT_WBC_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_HEMOLOBIN_CONCENTRATION.ID] = &CONCEPT_HEMOLOBIN_CONCENTRATION
	DEFAULT_CONCEPT_REPO[CONCEPT_MVC.ID] = &CONCEPT_MVC
	DEFAULT_CONCEPT_REPO[CONCEPT_MCH.ID] = &CONCEPT_MCH
	DEFAULT_CONCEPT_REPO[CONCEPT_MCHC.ID] = &CONCEPT_MCHC
	DEFAULT_CONCEPT_REPO[CONCEPT_PLATELET_COUNT.ID] = &CONCEPT_PLATELET_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_NEUTROPHIL_COUNT.ID] = &CONCEPT_NEUTROPHIL_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_LYMPHOCYTE_COUNT.ID] = &CONCEPT_LYMPHOCYTE_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_MONOCYTE_COUNT.ID] = &CONCEPT_MONOCYTE_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_EOSINOPHIL_COUNT.ID] = &CONCEPT_EOSINOPHIL_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_BASOPHIL_COUNT.ID] = &CONCEPT_BASOPHIL_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_RETICULOCYTE_COUNT.ID] = &CONCEPT_RETICULOCYTE_COUNT
	DEFAULT_CONCEPT_REPO[CONCEPT_WEATHER_IS_RAINING.ID] = &CONCEPT_WEATHER_IS_RAINING
}
